// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2_Bs-wy72H7z2iNI1LMUsD3k9kdh0ak',
    appId: '1:469642968518:web:01babc7c1c60e99e3446c7',
    messagingSenderId: '469642968518',
    projectId: 'yemektarif-c2a64',
    authDomain: 'yemektarif-c2a64.firebaseapp.com',
    storageBucket: 'yemektarif-c2a64.appspot.com',
    measurementId: 'G-LBJ2SFFDLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBin6ccrtZho-BmLEzMZIZckiQoVHxAuH8',
    appId: '1:469642968518:android:44ecb05b898d58963446c7',
    messagingSenderId: '469642968518',
    projectId: 'yemektarif-c2a64',
    storageBucket: 'yemektarif-c2a64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-CqFRD1ikzuXdPoVTjaJemCVJ72GsWc',
    appId: '1:469642968518:ios:66f171e2cf892bb43446c7',
    messagingSenderId: '469642968518',
    projectId: 'yemektarif-c2a64',
    storageBucket: 'yemektarif-c2a64.appspot.com',
    iosClientId: '469642968518-rq7b92tc00c1bot4nn724uual88e6qfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.izleme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS-CqFRD1ikzuXdPoVTjaJemCVJ72GsWc',
    appId: '1:469642968518:ios:66f171e2cf892bb43446c7',
    messagingSenderId: '469642968518',
    projectId: 'yemektarif-c2a64',
    storageBucket: 'yemektarif-c2a64.appspot.com',
    iosClientId: '469642968518-rq7b92tc00c1bot4nn724uual88e6qfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.izleme',
  );
}
